---
- name: Request or Renew Let's Encrypt SSL certificate
  hosts: localhost
  gather_facts: no

  vars:
    target_host: "trinetra.home.arpa"
    remote_user: "ciadmin"
    credentials_file_path: "/home/ciadmin/dynu-credentials.ini"
    dynu_api_key: "{{ lookup('env', 'DYNU_API_KEY') }}"
    domain_name: "trinetra.camdvr.org" # TODO: Replace with your domain name
    email_address: "gurucp2005@gmail.com" # TODO: Replace with your email

  tasks:
    - name: Ensure python3-pip is installed on the target
      ansible.builtin.apt:
        name: python3-pip
        state: present
        update_cache: yes
      become: yes # This tells Ansible to use sudo
      delegate_to: "{{ remote_user }}@{{ target_host }}"

    - name: Ensure Certbot and Dynu plugin are installed
      ansible.builtin.pip:
        name:
          - certbot
          - certbot-dns-dynu
        state: present
        extra_args: --break-system-packages
      delegate_to: "{{ remote_user }}@{{ target_host }}"

    - name: Manage Certbot process
      block:
        - name: Create temporary credentials file on target
          ansible.builtin.copy:
            content: "dns_dynu_auth_token = {{ dynu_api_key }}"
            dest: "{{ credentials_file_path }}"
            mode: '0600'
          delegate_to: "{{ remote_user }}@{{ target_host }}"

        - name: Run Certbot on target
          ansible.builtin.command:
            cmd: >
              python3 -m certbot certonly
              --authenticator dns-dynu
              --dns-dynu-credentials {{ credentials_file_path }}
              -d {{ domain_name }}
              --agree-tos
              --email {{ email_address }}
          become: yes # Run Certbot with sudo
          delegate_to: "{{ remote_user }}@{{ target_host }}"

      always:
        - name: Clean up credentials file on target
          ansible.builtin.file:
            path: "{{ credentials_file_path }}"
            state: absent
          delegate_to: "{{ remote_user }}@{{ target_host }}"
